import Dashboard from "./components/header/Header"
import "./globals.css"
import { ReduxProvider } from "@/redux/provider"

export const metadata = {
  title: 'Fake-store',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk">
      <body>
        <ReduxProvider>
        <Dashboard />
        <main>{children}</main>
        </ReduxProvider>
      </body>
    </html>
  )
}
